### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by outside-BUPT** [THUDM/ComiRec#27]

**Comment by outside-BUPT** [comment]
python=3.6.9
tensorflow-gpu=1.8.0
faiss-gpu =1.7.1

When I run the code, the error output is as follows:
Traceback (most recent call last):
  File "src/train.py", line 16, in <module>
    from model import *
  File "/home/ypy/rec_sys/ComiRec/src/model.py", line 5, in <module>
    from tensorflow.nn.rnn_cell import GRUCell
ModuleNotFoundError: No module named 'tensorflow.nn'
